
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DATA_FOLDER: /data
      DATABASE_MAX_CONNS: 10
      WEB_VAULT_ENABLED: "true"
      DOMAIN: ${DOMAIN}
    volumes:
      - /home/deploy/homelab/services/vaultwarden/data:/data
    ports:
      - "10.0.20.2:80:80"
