services:
  db:
    image: mariadb:11.8.9
    restart: always
    command: --transaction-isolation=READ-COMMITTED
    volumes:
      - db:/var/lib/mysql
    env_file: .env
  redis:
    image: redis:8.10.2-alpine
    restart: always

  app:
    image: nextcloud:33.0.9
    restart: always
    ports:
      - "10.0.20.2:8337:80"
    depends_on:
      - redis
      - db
    volumes:
      - nextcloud:/var/www/html
      - /mnt/nextcloud-smb:/var/www/html/data
    env_file: .env
    networks:
      - default
      - shared-infra
volumes:
  nextcloud:
  db:
networks:
  default:
    ipam:
      config:
        - subnet: 172.16.13.0/24
  shared-infra:
    external: true
    name: shared-infra