services:
  trilium:
    image: triliumnext/trilium:latest
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    ports:
      - '8181:8080'
    volumes:
      - /mnt/docker-nfs/trillium:/home/node/trilium-data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro